
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhfukgqkaijailpwpcdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oZnVrZ3FrYWlqYWlscHdwY2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODE2MzksImV4cCI6MjA1ODQ1NzYzOX0.qlpqn-yOrxJsxEhwr6ZALLCWa1tNHD7HM-acE5Fsfw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
